// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	UserID    uuid.UUID
	Username  string
	Password  string
	CreatedAt time.Time
}
