// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: parkareas.sql

package database

import (
	"context"
)

const getAllParkAreas = `-- name: GetAllParkAreas :many
SELECT id, name FROM park_areas
`

func (q *Queries) GetAllParkAreas(ctx context.Context) ([]ParkArea, error) {
	rows, err := q.db.QueryContext(ctx, getAllParkAreas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParkArea
	for rows.Next() {
		var i ParkArea
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
